### ISSUE TITLE
Allow user to modify Gripper Brackets urdf

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/prbt_grippers#6]
If the user includes pg70 urdf, default gripper brackets are loaded.
It would be desired, to allow the user, to include / attach his own gripper brackets.

Therefore I'd suggest, to move the [brackets-include](https://github.com/PilzDE/prbt_grippers/blob/6111f3116129387304c852438bcced615647099c/prbt_pg70_support/urdf/pg70.urdf.xacro#L32) into from the gripper-urdf into prbt_support. A user writing his own application.urdf.xacro could then easily replace it with custom brackets.

_Originally posted by @rfeistenauer in https://github.com/PilzDE/pilz_templates/pull/1#issuecomment-477983571_

**Comment by martiniil** [comment]
Is there anything preventing the user from attaching his own brackets as you describe?

I am not entirely convinced, since the default brackets are not applicable in a general case (my guess, what if the included gripper has only one finger?) With this in mind, I would rather suggest to exclude `simple_gripper_brackets.urdf.xacro` from prbt_support.

**Comment by jschleicher** [comment]
Because of [the include inside pg70.urdf.xacro](https://github.com/PilzDE/prbt_grippers/blob/6111f3116129387304c852438bcced615647099c/prbt_pg70_support/urdf/pg70.urdf.xacro#L32), the user currently cannot include pg70.urdf.xacro without the default brackets.
